#!/bin/bash
set -e
current_branch=$(git branch --show-current)

if [[ $current_branch == "main" || $current_branch == "master" ]]; then
  echo "You are trying to commit to main branch, add flag --no-verify to bypass the git hook !!"
  exit 1
fi

######## KTLINT-GRADLE HOOK START ########

    CHANGED_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $2 ~ /\.kts|\.kt/ { print $2}')"

    if [ -z "$CHANGED_FILES" ]; then
        echo "No Kotlin staged files."
        exit 0
    fi;

    echo "Running ktlintCheck over these files:"
    echo "$CHANGED_FILES"

    ./gradlew --quiet ktlintCheck -PinternalKtlintGitFilter="$CHANGED_FILES"

    echo "Completed ktlint run."
    echo "$CHANGED_FILES" | while read -r file; do
    if [ -f $file ]; then
        git add $file
    fi
done
    echo "Completed ktlint hook."
######## KTLINT-GRADLE HOOK END ########
