version: '3.6'
services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: supersecurepassword
    ports:
      - 5432:5432
  keycloak:
    image: quay.io/keycloak/keycloak
    command: [ "start-dev", "--import-realm" ]
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8081:8080
    volumes:
      - ./local/realm.json:/opt/keycloak/data/import/realm.json:ro
  app:
    image: ghcr.io/ablil/spring-starter:latest
    container_name: springstarter_app
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_PASSWORD: supersecurepassword
      DB_HOST: database
      host: localhost
      URL: http://localhost
