version: '3.6'
services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: &dbpassword supersecurepassword
    ports:
      - "5432:5432"
  keycloak:
    image: quay.io/keycloak/keycloak
    command:
      - start-dev
      - --import-realm
      - --proxy=edge
      - --hostname-strict=false
      - --hostname-strict-https=false
      - --proxy-headers=forwarded
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8081
    ports:
      - "8081:8081"
    volumes:
      - ./local/realm.json:/opt/keycloak/data/import/realm.json:ro
  app:
#    image: spring-starter
    image: ghcr.io/ablil/spring-starter:latest
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_PASSWORD: *dbpassword
      DB_HOST: database
      KC_HOST: keycloak
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - keycloak
      - app