version: '3'
services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: supersecurepassword
  app:
    build:
      context: .
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PASSWORD: supersecurepassword
      SPRING_PROFILES_ACTIVE: prod

  web:
    build:
      context: web
    environment:
      NODE_ENV: production
    depends_on:
      - app
  nginx:
    image: nginx
    depends_on:
      - web
      - app
    volumes:
      - $PWD/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
