version: '3'
services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: supersecurepassword

  app:
    build:
      context: .
    depends_on:
      - database
    ports:
      - 80:80
    environment:
      DB_HOST: database
      DB_PASSWORD: supersecurepassword


