version: '3'
services:
  database:
    image: postgres
    container_name: springstarter_database
    environment:
      POSTGRES_PASSWORD: supersecurepassword
    ports:
      - 5432:5432
  smtp-server:
    image: mailhog/mailhog
    container_name: fake-smtp
    ports:
      - 1025:1025
      - 8025:8025
  app:
    image: ghcr.io/ablil/spring-starter:latest
    container_name: springstarter_app
    depends_on:
      - database
      - smtp-server
    ports:
      - "8080:80"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_PASSWORD: supersecurepassword
      DB_HOST: database
      host: localhost
      URL: http://localhost
