spring:
  application:
    name: springstarter
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:supersecurepassword}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:0.0.0.0}:${DB_PORT:5432}/${DB_NAME:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KC_HOST:0.0.0.0}:8081/realms/${KC_REALM:springstarter}/protocol/openid-connect/certs

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: info,env,health