spring:
  config:
    import: classpath:application-common.yml
  datasource:
    username: postgres
    password: supersecurepassword
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    protocol: smtp
    host: sandbox.smtp.mailtrap.io
    username: b9d60767eb31db
    password: 2a9bc9427c08f0
    port: 2525
    properties:
      mail:
        smtp:
          ssl: true
          starttls:
            enable: true

server:
  port: 8080

logging:
  pattern:
    console: "%clr(${LOG_LEVEL_PATTERN:%p}) %clr(%logger){cyan} %clr([%M]){magenta}  %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    com.ablil: DEBUG

#debug: true