spring:
  application:
    name: springstarter
  main:
    banner-mode: off

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json


server:
  error:
    whitelabel:
      enabled: false