spring:
  config:
    import: application.yml
  datasource:
    password: supersecurepassword
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 8080