spring:
  config:
    import: application-common.yml
  datasource:
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:postgres}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: ${ADMIN_USER:admin}
      password: ${ADMIN_PASSWORD:admin}
      roles: ADMIN

server:
  port: 80

ablil:
  domain-name: ${DOMAIN_NAME}