spring:
  profiles:
    default: dev
  application:
    name: springstarter

  datasource:
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    protocol: smtp
    host: sandbox.smtp.mailtrap.io
    username: b9d60767eb31db
    password: 2a9bc9427c08f0
    port: 2525
    properties:
      mail:
        smtp:
          ssl: true
          starttls:
            enable: true

server:
  port: ${PORT:80}

springdoc:
  default-produces-media-type: application/json