spring:
  mail:
    protocol: smtp
    host: 0.0.0.0
    port: 1025

logging:
  pattern:
    console: "%clr(${LOG_LEVEL_PATTERN:%p}) %clr(%logger){cyan} %clr([%M]){magenta}  %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    com.ablil: DEBUG
