openapi: 3.0.3
info:
  version: '1.0.0'
  title: Login and Password reset API
tags:
  - name: login
    description: Login
paths:
  /api/auth/login:
    post:
      operationId: login
      tags:
        - login
      summary: login
      description: "Login with username and password and return json web token"
      requestBody:
        description: 'credentials'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        200:
          description: "logged in successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        403:
          description: "invalid credentials"

components:
  schemas:
    Token:
      type: object
      properties:
        token:
          type: string
          example: "Json web token (jwt)"
      required:
        - token
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password