openapi: 3.0.3
info:
  version: '1.0.0'
  title: Health API
tags:
  - name: health
    description: Health check
paths:
  /health:
    get:
      tags:
        - health
      description: Returns 'OK' indicating the health of the service.
      responses:
        200:
          description: Successful response
          content:
            text/plain:

              schema:
                type: string
                example:
                  text/plain: 'OK'
