openapi: 3.0.3
info:
  version: '1.0.0'
  title: Login and Password reset API
tags:
  - name: password
    description: Password reset process
paths:
  /api/auth/forget_password:
    post:
      operationId: forgetPassword
      tags:
        - password
      summary: "Trigger forget password process"
      description: "Trigger forget password process and send email with reset password link"
      requestBody:
        required: true
        description: 'email'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgetPasswordRequest'
      responses:
        200:
          description: "reset password link sent via email successfully"

  /api/auth/reset_password:
    post:
      operationId: resetPassword
      tags:
        - password
      summary: "Reset password"
      description: "Reset password with new password"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
      responses:
        200:
          description: "password reset successfully"


components:
  schemas:
    ResetPasswordRequest:
      type: object
      properties:
        token:
          type: string
        password:
          type: string
      required: ['token', 'password']
    ForgetPasswordRequest:
      type: object
      properties:
        email:
          type: string
      required: ['email']