openapi: 3.0.3
info:
  version: '1.0.0'
  title: Login and Password reset API
tags:
  - name: password
    description: Password reset process
paths:
  /auth/forget_password:
    post:
      tags:
        - password
      summary: "Trigger forget password process"
      description: "Trigger forget password process and send email with reset password link"
      requestBody:
        required: true
        description: 'email'
        content:
          application/json:
            schema:
              type: object
              required: ['email']
              properties:
                email:
                  type: string
      responses:
        200:
          description: "reset password link sent via email successfully"
  /auth/reset_password:
    post:
      tags:
        - password
      summary: "Reset password"
      description: "Reset password with new password"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: ['token', 'password']
              properties:
                token:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: "password reset successfully"