openapi: 3.0.3
info:
  title: Registration
  description: Registration
  version: 1.0.0
tags:
  - name: Registration
    description: Registration
paths:
  /api/auth/register:
    post:
      tags:
        - Registration
      summary: Register a new user
      operationId: registerNewUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationRequest'
      responses:
        '201':
          description: OK
  /api/auth/register/confirm:
    get:
      tags:
        - Registration
      operationId: confirmRegistration
      summary: Confirm registration
      description: Confirm registration given valid token and redirect user after confirmation
      parameters:
        - name: token
          in: query
          description: Token to confirm registration
          required: true
          schema:
            type: string
      responses:
        '307':
          description: Temporary Redirect

  /api/auth/forget_password:
    post:
      operationId: sendPasswordResetLink
      tags:
        - Registration
      summary: "Send password reset link"
      description: "Send password reset link via email, if account does not exist, do nothing"
      requestBody:
        required: true
        description: 'email'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgetPasswordRequest'
      responses:
        200:
          description: "reset password link sent via email successfully"

  /api/auth/reset_password:
    post:
      operationId: updateUserPassword
      tags:
        - Registration
      summary: "Update or reset user password"
      description: "A reset token is required to reset password, token is sent via email"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
      responses:
        200:
          description: "password reset successfully"

components:
  schemas:
    RegistrationRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
          minLength: 10
        username:
          type: string
          minLength: 6
      required:
        - username
        - password
        - email
    ResetPasswordRequest:
      type: object
      properties:
        token:
          type: string
        password:
          type: string
      required: ['token', 'password']
    ForgetPasswordRequest:
      type: object
      properties:
        email:
          type: string
      required: ['email']
