openapi: 3.0.3
info:
  version: '1.0.0'
  title: Users management

tags:
  - name: user
    description: Users management
paths:
  /api/users/{userId}:
    get:
      tags:
        - user
      operationId: getUser
      summary: "Get user by id"
      description: "Fetch user by internal identifier"
      parameters:
        - name: userId
          in: path
          description: ID of the user to return
          required: true
          schema:
            type: number
            format: int64
      responses:
        200:
          description: "reset password link sent via email successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'


components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        username:
          type: string
        status:
          type: string
        role:
          type: string
          enum: [ 'ADMIN', 'DEFAULT', 'TECHNICAL' ]
      required: [ 'id', 'email', 'username', 'lastName', 'status', 'role' ]