name: Cleanup


on:
  schedule:
    - cron: '0 0 1 * *' # every month

permissions:
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          package-name: spring-starter
          package-type: container
          min-versions-to-keep: 1
          ignore-versions: 'latest'
